var menudata={children:[
{text:"Hauptseite",url:"index.htm"},
{text:"Zusätzliche Informationen",url:"pages.htm"},
{text:"Pakete",url:"namespaces.htm",children:[
{text:"Pakete",url:"namespaces.htm"}]},
{text:"Klassen",url:"annotated.htm",children:[
{text:"Auflistung der Klassen",url:"annotated.htm"},
{text:"Klassen-Verzeichnis",url:"classes.htm"},
{text:"Klassenhierarchie",url:"inherits.htm"},
{text:"Klassen-Elemente",url:"functions.htm",children:[
{text:"Alle",url:"functions.htm",children:[
{text:"a",url:"functions.htm#index_a"},
{text:"c",url:"functions.htm#index_c"},
{text:"d",url:"functions.htm#index_d"},
{text:"e",url:"functions.htm#index_e"},
{text:"g",url:"functions.htm#index_g"},
{text:"h",url:"functions.htm#index_h"},
{text:"i",url:"functions.htm#index_i"},
{text:"l",url:"functions.htm#index_l"},
{text:"m",url:"functions.htm#index_m"},
{text:"n",url:"functions.htm#index_n"},
{text:"o",url:"functions.htm#index_o"},
{text:"p",url:"functions.htm#index_p"},
{text:"r",url:"functions.htm#index_r"},
{text:"s",url:"functions.htm#index_s"},
{text:"t",url:"functions.htm#index_t"}]},
{text:"Funktionen",url:"functions_func.htm",children:[
{text:"a",url:"functions_func.htm#index_a"},
{text:"c",url:"functions_func.htm#index_c"},
{text:"d",url:"functions_func.htm#index_d"},
{text:"e",url:"functions_func.htm#index_e"},
{text:"g",url:"functions_func.htm#index_g"},
{text:"h",url:"functions_func.htm#index_h"},
{text:"i",url:"functions_func.htm#index_i"},
{text:"l",url:"functions_func.htm#index_l"},
{text:"m",url:"functions_func.htm#index_m"},
{text:"n",url:"functions_func.htm#index_n"},
{text:"o",url:"functions_func.htm#index_o"},
{text:"p",url:"functions_func.htm#index_p"},
{text:"r",url:"functions_func.htm#index_r"},
{text:"s",url:"functions_func.htm#index_s"},
{text:"t",url:"functions_func.htm#index_t"}]},
{text:"Variablen",url:"functions_vars.htm"}]}]},
{text:"Dateien",url:"files.htm",children:[
{text:"Auflistung der Dateien",url:"files.htm"}]}]}
